language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
  - stable

before_script:
  - cargo install cargo-kcov
  - cargo kcov --print-install-kcov-sh | $SHELL

script:
  - cargo kcov --all --coveralls
  - cargo build --release
  - cargo run --release
